name: Backend CD
on:
  push:
    branches: 
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: WAS 인스턴스 접속 및 애플리케이션 실행
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop $(docker ps -a -q) 
            sudo docker rm $(docker ps -a -q) 
            sudo docker pull jeongwoon1849/bookitty
            sudo docker run -d -p 8080:8080 --name new jeongwoon1849/bookitty
